name: EachOneTeachOne
version: 1.0
description: School based teaching plugin for ease of use.
authors: [Synapz_]
main: me.synapz.eoto.EOTO

commands:
   eachoneteachone:
      description: Open EOTO command menu
      aliases: [eoto, teacher]